#!/bin/bash

subsubtile () {
	zoom[$1]=$(($1+1))
	x[$1]=$(($2*2))
	y[$1]=$(($3*2))
	dx[$1]=$4
	dy[$1]=$5
	z[$1]=$((2**${zoom[$1]}))
	for ((i[$1]=0; ${i[$1]}<2; i[$1]=${i[$1]}+1)); do
		for ((j[$1]=0; ${j[$1]}<2; j[$1]=${j[$1]}+1)); do
			xs=$((${x[$1]}+${i[$1]}))
			ys=$((${y[$1]}+${j[$1]}))
			mkdir -p sport_tiles/${zoom[$1]}/$xs
			tilename="sport_tiles/${zoom[$1]}/$xs/$ys.png"
			m=$((${z[$1]}/4096))
			bpi=$((90*$m))
			xy=$((256/$m))
			x0=$((${dx[$1]}+(${i[$1]}*$xy)))
			y0=$(((${dy[$1]}-$xy)-(${j[$1]}*$xy)))
			x1=$(((${dx[$1]}+$xy)+(${i[$1]}*$xy)))
			y1=$((${dy[$1]}-(${j[$1]}*$xy)))
			inkscape tmp/panel_${zoom[$1]}.svg -e $tilename -d $bpi -a $x0:$y0:$x1:$y1 -y 0 -b "#000000" 1>/dev/null 2>/dev/null
      if [ -e $tilename ]; then
        if [ $(stat "$tilename" | cut -f 8 -d' ') -lt 410 ]; then
          rm $tilename
          if [ ${zoom[$1]} -lt 15 ]; then
            subsubtile ${zoom[$1]} $xs $ys $x0 $y1
          fi
        else
          echo "put $tilename cache/$(echo $tilename | sed -e s?/?-?g)" >> tmp/$1-$2-$3.send
          if [ ${zoom[$1]} -lt 18 ]; then
            subsubtile ${zoom[$1]} $xs $ys $x0 $y1
          fi
        fi
      fi
		done
	done
}

subsubtile $1 $2 $3 $4 $5
