#!/bin/bash

clean () {
  zoom[$1]=$(($1+1))
  x[$1]=$(($2*2))
  y[$1]=$(($3*2))
  for ((i[$1]=0; ${i[$1]}<2; i[$1]=${i[$1]}+1)); do
    for ((j[$1]=0; ${j[$1]}<2; j[$1]=${j[$1]}+1)); do
      xc=$((${x[$1]}+${i[$1]}))
      yc=$((${y[$1]}+${j[$1]}))
      cleanname="sport_tiles/${zoom[$1]}/$xc/$yc.png"
      if [ -e $cleanname ]; then
        rm $cleanname
        echo "rm $cleanname" >> tmp/deletions
      fi
      if [ ${zoom[$1]} -lt 18 ]; then
        clean ${zoom[$1]} $xc $yc
      fi
    done
  done
}

subtile () {
	zoom[$1]=$(($1+1))
	x[$1]=$(($2*2))
	y[$1]=$(($3*2))
	dx[$1]=$4
	dy[$1]=$5
	z[$1]=$((2**${zoom[$1]}))
	for ((i[$1]=0; ${i[$1]}<2; i[$1]=${i[$1]}+1)); do
		for ((j[$1]=0; ${j[$1]}<2; j[$1]=${j[$1]}+1)); do
			xs=$((${x[$1]}+${i[$1]}))
			ys=$((${y[$1]}+${j[$1]}))
			mkdir -p sport_tiles/${zoom[$1]}/$xs
			tilename="sport_tiles/${zoom[$1]}/$xs/$ys.png"
			m=$((${z[$1]}/4096))
			bpi=$((90*$m))
			xy=$((256/$m))
			x0=$((${dx[$1]}+(${i[$1]}*$xy)))
			y0=$(((${dy[$1]}-$xy)-(${j[$1]}*$xy)))
			x1=$(((${dx[$1]}+$xy)+(${i[$1]}*$xy)))
			y1=$((${dy[$1]}-(${j[$1]}*$xy)))
			inkscape tmp/panel_${zoom[$1]}.svg -e $tilename -d $bpi -a $x0:$y0:$x1:$y1 -y 0 -b "#000000" 1>/dev/null 2>/dev/null
      if [ -e $tilename ]; then
        if [ $(stat "$tilename" | cut -f 8 -d' ') -lt 410 ]; then
          rm $tilename
          if [ ${zoom[$1]} -lt 15 ]; then
            subtile ${zoom[$1]} $xs $ys $x0 $y1
          fi
        else
          echo "put $tilename cache/$(echo $tilename | sed -e s?/?-?g)" >> tmp/$1-$2-$3.send
          if [ ${zoom[$1]} -lt 18 ]; then
            subtile ${zoom[$1]} $xs $ys $x0 $y1
          fi
        fi
      fi
		done
	done
}

tile () {
  tx=$(echo $1 | cut -f 1 -d'_')
  ty=$(echo $1 | cut -f 2 -d'_')
  bb=$(echo $1 | cut -f 3 -d'_')
	for k in {12..18}; do
		perl ../orp/orp.pl -r ../SeaMapStyles/osm-seamark-sport-z$k.xml -b $bb -o tmp/panel_$k.svg tmp/$1 2>/dev/null
	done;
  filename="sport_tiles/12/$tx/$ty.png"
  if [ -e $filename ]; then
    echo "rm $filename" >> tmp/deletions
  fi
  clean 12 $tx $ty
	mkdir -p sport_tiles/12/$tx
	inkscape tmp/panel_12.svg -e $filename -d 90 -a 256:256:512:512 -y 0 -b "#000000" 1>/dev/null 2>/dev/null
  if [ -e $filename ]; then
    if [ $(stat "$filename" | cut -f 8 -d' ') -lt 410 ]; then
      rm $filename
    else
      echo "put $filename cache/$(echo $filename | sed -e s?/?-?g)" >> tmp/12-$tx-$ty.send
    fi
  fi
	subtile 12 $tx $ty 256 512
  echo "$tx $ty $(date)"
}

while true; do
  if [ $(ls tmp | grep -c "\_12\.osm") -eq 0 ]; then
    sleep 10
  else
	  for file in $(ls tmp | grep "\_12\.osm"); do
  	  if [ -e pause ]; then
    		echo "Paused"
			  while [ -e pause ]; do
  				sleep 60
  			done
    		break
    	fi
    	tile $file
    	if [ -e tmp/$file ] ; then
	    	rm tmp/$file
	    fi
  	done
  fi
done
