#!/bin/bash

clean () {
  zoom[$1]=$(($1+1))
  x[$1]=$(($2*2))
  y[$1]=$(($3*2))
  for ((i[$1]=0; ${i[$1]}<2; i[$1]=${i[$1]}+1)); do
    for ((j[$1]=0; ${j[$1]}<2; j[$1]=${j[$1]}+1)); do
      xc=$((${x[$1]}+${i[$1]}))
      yc=$((${y[$1]}+${j[$1]}))
      cleanname="tiles/${zoom[$1]}/$xc/$yc.png"
      if [ -e $cleanname ]; then
				echo "rm $cleanname"
        rm $cleanname
        echo "rm $cleanname" >> tmp/clear.tmp
      fi
      if [ ${zoom[$1]} -lt 18 ]; then
        clean ${zoom[$1]} $xc $yc
      fi
    done
  done
}

cleanname="tiles/$1/$2/$3.png"
if [ -e $cleanname ]; then
	echo "rm $cleanname"
  rm $cleanname
  echo "rm $cleanname" >> tmp/clear.tmp
fi
clean $1 $2 $3
if [ -e tmp/clear.tmp ]; then
  mv tmp/clear.tmp tmp/clear.send
fi

