#!/bin/bash

while true; do
  if [ $(ls tmp | grep -c "\_12\.osm") -eq 0 ]; then
    if [ -e rrx ]; then
      x=$(cat rrx)
    else
      x=0
    fi
    if [ -e rry ]; then
      y=$(cat rry)
    else
      y=0
    fi
    while true; do
      y=$(($y+1))
      if [ $y -eq 4096 ]; then
        x=$(($x+1))
        y=0
        if [ $x -eq 4096 ]; then
          x=0
        fi
      fi
      if [ -e tiles/12/$x/$y.png ]; then
        rr=1;
      else
        rr=0;
        for ((i=0; $i<2; i=$i+1)); do
         for ((j=0; $j<2; j=$j+1)); do
            tx=$(($x*2+$i))
            ty=$(($y*2+$j))
            if [ -e tiles/13/$tx/$ty.png ]; then
              rr=1
              break
            fi
          done
        done    
        if [ $rr -eq 0 ]; then
          for ((i=0; $i<4; i=$i+1)); do
            for ((j=0; $j<4; j=$j+1)); do
              tx=$(($x*4+$i))
              ty=$(($y*4+$j))
              if [ -e tiles/14/$tx/$ty.png ]; then
                rr=1
                break
              fi
            done
          done    
        fi
      fi
      if [ $rr -ne 0 ]; then
        tile=$(echo "scale=10; ($x-1)" | bc)
        tile=$(echo "scale=10; if ($tile < 0) $tile+4096 else $tile" | bc)
        minlon=$(echo "scale=10; (($tile/4096)*360)-180" | bc)
        tile=$(echo "scale=10; ($x+2)" | bc)
        tile=$(echo "scale=10; if ($tile >= 4096) $tile-4096 else $tile" | bc)
        maxlon=$(echo "scale=10; (($tile/4096)*360)-180" | bc)
        tile=$(echo "scale=10; ($y-1)" | bc -l)
        tile=$(echo "scale=10; if ($tile < 0) 0 else $tile" | bc)
        yx=$(echo "scale=10; 4*a(1)*(1-((2*$tile)/4096))" | bc -l)
        maxlat=$(echo "scale=10; ((a((e($yx)-(1/e($yx)))/2))*180)/(4*a(1))" | bc -l)
        tile=$(echo "scale=10; ($y+2)" | bc -l)
        tile=$(echo "scale=10; if ($tile >= 4096) 4095 else $tile" | bc)
        yx=$(echo "scale=10; 4*a(1)*(1-((2*$tile)/4096))" | bc -l)
        minlat=$(echo "scale=10; ((a((e($yx)-(1/e($yx)))/2))*180)/(4*a(1))" | bc -l)
		    if [ $minlat = 0 ]; then minlat=-85.0; fi
        osmosis -q --rx file=tmp/panel-z0.osm --bb top=$maxlat left=$minlon bottom=$minlat right=$maxlon completeWays=yes --wx file=tmp/panel-rr.osm 2> /dev/null
        bb="$minlat,$minlon,$maxlat,$maxlon"
        cp tmp/panel-rr.osm tmp/$x\_$y\_$bb\_12.osm
        echo "$x" > rrx
        echo "$y" > rry
        break
      fi
    done
 	fi
	sleep 60
done
