#!/bin/bash

while true; do
  if [ ./Overpass/translate_xapi "*[seamark:type=*][@meta]" | ./Overpass/osm3s_query > tmp.osm 2> /dev/null ]; then
  	cp tmp.osm world.osm
	  mv tmp.osm next.osm
	else
	  sleep 60
	fi
done
