#!/bin/bash

while true; do
  while [ -e next.osm ]; do
    sleep 30
  done
  echo "[timeout:3600];(rel['seamark:type'];>;way['seamark:type'];>;node['seamark:type'];);out meta;" | ./Overpass/osm3s_query > xapi.osm 2> /dev/null
  mv xapi.osm next.osm
done
