#!/bin/bash

while true; do
	while [ ! -e next.osm ]; do
    sleep 10
	done
	echo "$(date) Parse world data" >> log.txt
	if [ $(echo $(date "+%M"|sed 's/^0//')) -lt 5 ]; then
  	java -jar jharbour.jar <world.osm >harbours.xml
	  scp -q -C -P 2215 harbours.xml mherring@t1.openseamap.org:~/tiles/
	  echo "$(date) Harbours uploaded" >> log.txt
  	if [ $(echo $(date "+%H"|sed 's/^0//')) -eq 0 ]; then
  	  scp -q -C -P 2215 world.osm mherring@t1.openseamap.org:~/tiles/
  	  echo "$(date) World uploaded" >> log.txt
  	fi
	fi
	diff world.osm next.osm | grep id= | grep -v "<tag" > diffs
	java -jar jsearch.jar ./
	mv next.osm world.osm
  if [ -s diffs ]; then
    echo "$(date) New rendering queued" >> log.txt
  else
    echo "$(date) No changes" >> log.txt
  fi
	if [ -e stop ]; then
		echo "$(date) Stopped" >> log.txt
		exit
	fi
	if [ -e pause ]; then
		echo "$(date) Paused" >> log.txt
		while [ -e pause ]; do
			sleep 300
		done
		echo "$(date) Resumed" >> log.txt
	fi
done
