#!/bin/bash

subsearch () {
  zoom[$1]=$(($1+1))
  x[$1]=$(($2*2))
  y[$1]=$(($3*2))
  z[$1]=$((2**${zoom[$1]}))
  for ((i[$1]=0; ${i[$1]}<2; i[$1]=${i[$1]}+1)); do
    for ((j[$1]=0; ${j[$1]}<2; j[$1]=${j[$1]}+1)); do
      os=$(echo "scale=8; ${z[$1]}/4096" | bc)
      tile=$(echo "scale=8; (${x[$1]}+${i[$1]}-$os)" | bc)
      tile=$(echo "scale=8; if ($tile < 0) $tile+${z[$1]} else $tile" | bc)
      minlon=$(echo "scale=8; (($tile/${z[$1]})*360)-180" | bc)
      tile=$(echo "scale=8; (${x[$1]}+${i[$1]}+1+$os)" | bc)
      tile=$(echo "scale=8; if ($tile >= ${z[$1]}) $tile-${z[$1]} else $tile" | bc)
      maxlon=$(echo "scale=8; (($tile/${z[$1]})*360)-180" | bc)
      tile=$(echo "scale=8; (${y[$1]}+${j[$1]}-$os)" | bc -l)
      tile=$(echo "scale=8; if ($tile < 0) 0 else $tile" | bc)
      yx=$(echo "scale=8; 4*a(1)*(1-((2*$tile)/${z[$1]}))" | bc -l)
      maxlat=$(echo "scale=8; ((a((e($yx)-(1/e($yx)))/2))*180)/(4*a(1))" | bc -l)
      tile=$(echo "scale=8; (${y[$1]}+${j[$1]}+1+$os)" | bc -l)
      tile=$(echo "scale=8; if ($tile >= ${z[$1]}) ${z[$1]}-1 else $tile" | bc)
      yx=$(echo "scale=8; 4*a(1)*(1-((2*$tile)/${z[$1]}))" | bc -l)
      minlat=$(echo "scale=8; ((a((e($yx)-(1/e($yx)))/2))*180)/(4*a(1))" | bc -l)
			if [ $minlat = 0 ]; then minlat=-85.0; fi
      osmosis -q --rx file=tmp/panel-z$1.osm --bb top=$maxlat left=$minlon bottom=$minlat right=$maxlon completeWays=yes --wx file=tmp/panel-z${zoom[$1]}.osm
      timestamp=$(../util/checkdate tmp/panel-z${zoom[$1]}.osm)
      bb="$minlat,$minlon,$maxlat,$maxlon"
      tx=$((${x[$1]}+${i[$1]}))
      ty=$((${y[$1]}+${j[$1]}))
      if [ $timestamp \> $4 ]; then
        if [ ${zoom[$1]} -lt 12 ]; then
          subsearch ${zoom[$1]} $tx $ty $4
        else
          perl ../orp/orp.pl -r ../SeaMapStyles/osm-seamark-z12-15.xml -b $bb -o tmp/panel.svg tmp/panel-z12.osm 2>/dev/null
          inkscape tmp/panel.svg -e tmp/panel.png -d 90 -a 256:256:512:512 -y 0 -b "#000000" 1>/dev/null 2>/dev/null
          if [ -e tmp/panel.png ]; then
            if [ $(stat tmp/panel.png | cut -f 8 -d' ') -ge 410 ]; then
              cp tmp/panel-z12.osm tmp/$tx\_$ty\_$bb\_tile
            fi
          fi
        fi
      fi
    done
  done
}

subsearch $1 $2 $3 $4
