#!/bin/bash

clean () {
  zoom[$1]=$(($1+1))
  x[$1]=$(($2*2))
  y[$1]=$(($3*2))
  for ((i[$1]=0; ${i[$1]}<2; i[$1]=${i[$1]}+1)); do
    for ((j[$1]=0; ${j[$1]}<2; j[$1]=${j[$1]}+1)); do
      xc=$((${x[$1]}+${i[$1]}))
      yc=$((${y[$1]}+${j[$1]}))
      cleanname="tiles/${zoom[$1]}/$xc/$yc.png"
      if [ -e $cleanname ]; then
        rm $cleanname
        echo "rm $cleanname" >> tmp/deletions
      fi
      if [ ${zoom[$1]} -lt 18 ]; then
        clean ${zoom[$1]} $xc $yc
      fi
    done
  done
}

tile () {
	term=$(ps -p $$ | tail -1 | cut -f 4 -d' ')
  tx=$(echo $1 | cut -f 1 -d'_')
  ty=$(echo $1 | cut -f 2 -d'_')
  bb=$(echo $1 | cut -f 3 -d'_')
	while [ $(ps -a | grep -c inkscape) -gt 1 ]; do
		sleep 1
	done
	for k in {12..17}; do
		../searender/searender ../searender/symbols/symbols.svg $k $bb >tmp/panel_$k.svg <tmp/$1 &
	done;
		../searender/searender ../searender/symbols/symbols.svg 18 $bb >tmp/panel_18.svg <tmp/$1
  filename="tiles/12/$tx/$ty.png"
  if [ -e $filename ]; then
    echo "rm $filename" >> tmp/deletions
  fi
  clean 12 $tx $ty
	mkdir -p tiles/12/$tx
	inkscape tmp/panel_12.svg -e $filename -d 90 -a 256:256:512:512 -y 0 -b "#000000" 1>/dev/null 2>/dev/null
	while [ -e tmp/deletions ]; do
		sleep 1
	done
  if [ -e $filename ]; then
    if [ $(stat "$filename" | cut -f 8 -d' ') -lt 410 ]; then
      rm $filename
    else
      echo "put $filename cache/$(echo $filename | sed -e s?/?-?g)" >> tmp/12-$tx-$ty.send
    fi
  fi
	./subtile 12 $tx $ty 256 512
  while [ $(ps -a | grep -c inkscape) -gt 1 ]; do
		sleep 1
  done
  echo "$(date) rendered 12 $tx $ty" >> log.txt
}

tile91011() {
  for file in $(ls tmp | grep "tiles\-"); do
		tile=$(echo $file | sed -e s?-?/?g)
		if [ $(stat tmp/$file | cut -f 8 -d' ') -ge 410 ]; then
			mkdir -p $(dirname $tile)
			mv -f tmp/$file $tile
			echo "put $tile cache/$file" >> tmp/9-10-11.send
		else
			if [ -e $tile ]; then
				rm $tile
				echo "rm $tile" >> tmp/deletions
			fi
			rm tmp/$file
		fi
  done
}

while true; do
	tile91011
  if [ $(ls tmp | grep -c "\_12\.osm") -eq 0 ]; then
    sleep 1
  else
	  for file in $(ls tmp | grep "\_12\.osm"); do
  	  if [ -e hold ]; then
    		echo "Holding..."
			  while [ -e hold ]; do
  				sleep 60
  			done
  			echo "Resuming"
    		break
    	fi
    	tile $file
    	if [ -e tmp/$file ] ; then
	    	rm tmp/$file
	    fi
	    tile91011
  	done
  fi
done
