#!/bin/bash

clean () {
  zoom[$1]=$(($1+1))
  x[$1]=$(($2*2))
  y[$1]=$(($3*2))
  for ((i[$1]=0; ${i[$1]}<2; i[$1]=${i[$1]}+1)); do
    for ((j[$1]=0; ${j[$1]}<2; j[$1]=${j[$1]}+1)); do
      xc=$((${x[$1]}+${i[$1]}))
      yc=$((${y[$1]}+${j[$1]}))
      cleanname="tiles/${zoom[$1]}/$xc/$yc.png"
      if [ -e $cleanname ]; then
        rm $cleanname
        echo "rm $cleanname" >> tmp/deletions
      fi
      if [ ${zoom[$1]} -lt 18 ]; then
        clean ${zoom[$1]} $xc $yc
      fi
    done
  done
}

tile () {
  tx=$(echo $1 | cut -f 1 -d'_')
  ty=$(echo $1 | cut -f 2 -d'_')
  bb=$(echo $1 | cut -f 3 -d'_')
	while [ $(ps -a | grep -c subtile) -gt 1 ]; do
		sleep 1
	done
	for k in {12..18}; do
		perl ../orp/orp.pl -r ../SeaMapStyles/osm-seamark-z$k.xml -b $bb -o tmp/panel_$k.svg tmp/$1 2>/dev/null &
	done;
	while [ $(ps -a | grep -c perl) -gt 1 ]; do
		sleep 1
	done
  filename="tiles/12/$tx/$ty.png"
  if [ -e $filename ]; then
    echo "rm $filename" >> tmp/deletions
  fi
  clean 12 $tx $ty
	mkdir -p tiles/12/$tx
	inkscape tmp/panel_12.svg -e $filename -d 90 -a 256:256:512:512 -y 0 -b "#000000" 1>/dev/null 2>/dev/null
  if [ -e $filename ]; then
    if [ $(stat "$filename" | cut -f 8 -d' ') -lt 410 ]; then
      rm $filename
    else
      echo "put $filename cache/$(echo $filename | sed -e s?/?-?g)" >> tmp/12-$tx-$ty.send
    fi
  fi
	./subtile 12 $tx $ty 256 512 &
  echo "$tx $ty $(date)"
}

while true; do
  while [ $(ls tmp | grep -c "\_tile") -eq 0 ]; do
    sleep 10
  done
  for file in $(ls tmp | grep "\_tile"); do
    tile $file
    rm tmp/$file
  done
done
