#!/bin/bash

while true; do
	sleep 1
	if [ -e tmp/sending ]; then
		backoff=0
	  while [ $(ps -a | grep -c sftp) -gt 1 ]; do
      sleep 10
    done    
		while ! sftp -q -b tmp/sending malcolm@netz.smurf.noris.de; do
			echo "SFTP failure - retrying"
			touch hold
			backoff=$(($backoff+1))
			sleep $((60*$backoff))
		done
		rm tmp/sending
		rm -f hold
		echo $(date)
	fi
	while [ -e tmp/deletions ]; do
		mv tmp/deletions tmp/deleting
    while [ $(ps -a | grep -c sftp) -gt 1 ]; do
    	sleep 10
    done          
    sftp -q -b tmp/deleting malcolm@netz.smurf.noris.de
		rm tmp/deleting
  	sleep 20
	done
	if [ $(ls tmp | grep -c '.send') -ne 0 ]; then
		for file in $(ls tmp | grep '.send'); do
			mv tmp/$file tmp/send
			cat tmp/send >> tmp/sending
		done
		rm tmp/send
  	sleep 20
	fi
done
