#!/bin/bash

while true; do
	if [ -e sending ]; then
		backoff=0
		while ! sftp -q -b sending malcolm@netz.smurf.noris.de; do
			echo "SFTP failure - retrying"
			backoff=$(($backoff+1))
			sleep $((60*$backoff))
		done
		rm sending
	fi
	sleep 60
	while [ ! -e uploads ]; do
		sleep 60
	done
	mv uploads sending
done
